# Generated by Django 5.2.5 on 2025-09-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_zip_code_order_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default='0771114110', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='North', max_length=100),
            preserve_default=False,
        ),
    ]
