# Generated by Django 5.2.5 on 2025-09-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_mobile_number_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
